// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/rawkode/cue-talos/config/configpatcher

package configpatcher

// Input to the patch application process.
#Input: _

// Output of patch application process.
#Output: #Input
