// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/rawkode/cue-talos/config/configpatcher

// Package configpatcher provides methods to patch Talos config.
package configpatcher

// Patch is either JSON patch or strategic merge patch.
#Patch: _
