// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/rawkode/cue-talos/config/configpatcher

package configpatcher

import coreconfig "github.com/rawkode/cue-talos/config"

// StrategicMergePatch is a strategic merge config patch.
#StrategicMergePatch: {
	Provider: coreconfig.#Provider
}
