// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/rawkode/cue-talos/config/types/v1alpha1

package v1alpha1

// Base64Bytes implements YAML marshaling/unmarshaling via base64 encoding.
#Base64Bytes: _
