// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/rawkode/cue-talos/config/types/v1alpha1

package v1alpha1

// Version is the version string for v1alpha1.
#Version: "v1alpha1"
