// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/rawkode/cue-talos/config/types

// Package types imports all configuration document types to register them.
package types
