// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/rawkode/cue-talos/config/config

// Package config provides interfaces to consume machine configuration values.
package configt

// Config defines the interface to access contents of the machine configuration.
#Config: _
