// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/rawkode/cue-talos/config/config

package configt

// Document is a configuration document.
#Document: _

// NamedDocument is a configuration document which has a name.
#NamedDocument: _

// SecretDocument is a configuration document that contains secrets.
#SecretDocument: _
