// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/rawkode/cue-talos/config/config

package configt

// Encoder provides the interface to encode configuration documents.
#Encoder: _
