// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/rawkode/cue-talos/config/config

package configt

// SideroLinkConfig defines the interface to access SideroLink configuration.
#SideroLinkConfig: _
