// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/rawkode/cue-talos/config

// Package config provides methods to generate and consume Talos configuration.
package config

import "github.com/rawkode/cue-talos/config/configt"

// Config defines the interface to access contents of the machine configuration.
#Config: configt.#Config
