// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/rawkode/cue-talos/config/config

package config

// RuntimeConfig defines the interface to access Talos runtime configuration.
#RuntimeConfig: _

// WatchdogTimerConfig defines the interface to access Talos watchdog timer configuration.
#WatchdogTimerConfig: _

_#runtimeConfigWrapper: [...#RuntimeConfig]
