// Code generated by cue get go. DO NOT EDIT.

//cue:generate cue get go github.com/rawkode/cue-talos/config/config

package config

// Validator is the interface to validate configuration.
//
// Validator might be implemented by a Container and a single Document.
#Validator: _
